### PR TITLE
Modified insertion method of config secrets

### PR DESCRIPTION
**Pull request by Arthelon**
Node environment variables, injected through .env, cannot be accessed by the client. The solution is to create a config file on the client, which can be imported by other modules, that is hidden by .gitignore.

### CODE REVIEW

**Comment by bmorelli25** [comment]
Hey @Arthelon. Thanks for the PR.

Would you mind using the [Files Changed Tab](https://github.com/bmorelli25/React-Weather-App/pull/19/files) to add some comments to your code/PR? I'm having trouble understanding exactly what this code change does and what the geolocator is for. Thanks!

**Review by Arthelon — COMMENTED** [review]
To store config secrets, users will have to create a new app/config.js file following the app/configDefault.js file template. The README has also been updated with new instructions.

**Comment by Arthelon** [comment]
Sorry for the confusion, the geolocator is a later commit I made to fix #2. I've moved it to a separate branch so everything should be alright now.

**Comment by bmorelli25** [comment]
Okay got it. That's what was confusing me. Take a look at #5. I think this is a duplicate of that PR - just a different method. Correct?

**Comment by bmorelli25** [comment]
@Arthelon, I'm closing this PR as it is a duplicate of #5. Thanks for your submission. I'll add the Hacktoberfest label so you still get credit. Feel free to keep contributing!

**Pull request closed without merging**
