### PR TITLE
Add `dev` npm script task

### PR DESCRIPTION
**Pull request by jamesmacfie**
I want to lend a hand as part of Hacktoberfest and, specifically, https://github.com/bmorelli25/React-Weather-App/issues/14 but (taking a cue from some other projects I work on) know that we can run one npm script to start dev work instead of running both a webpack command (which requires webpack installed globally) and then starting the express server.

What I've done here:
- Installed the (concurrently)[https://www.npmjs.com/package/concurrently] package which means we can run two tasks at once
- Added webpack as a dev dependency so that we don't have to rely on the user having webpack installed globally
- Updated the readme with the new instructions

I know this wasn't listed as an issue specifically but it seemed like a useful thing to do ;)

### CODE REVIEW

**Comment by bmorelli25** [comment]
Thanks for the PR! Sorry it has taken me so long to get back to you on this one. I'm not entirely sold on this enhancement. While it doesn't require webpack to be installed globally, it does require concurrently to be installed globally, and I'm not sure that is entirely necessary. Either way the user is installing a global dependency. Thoughts?

I'll have some more time in the coming days and do some research on this.

**Comment by jamesmacfie** [comment]
`concurrently` comes via the locally installed module. I did find it odd that I had to call into webpack's `bin` folder to call it instead of just being able to call `webpack` from inside that npm script.

No bother if it's not an enhancement you want to put into the app

**Comment by bmorelli25** [comment]
Interesting, thanks! I'm not sold one way or the other yet. I'll look more into it tonight when I have more time. Sorry again for the delay on everything right now

**Comment by bmorelli25** [comment]
jamesmacfie I'm going to leave this out for now. Thanks for all of your contributions to the project during Hacktoberfest!

**Pull request closed without merging**
