### PR TITLE
Slight design changes, also extended dateFormatter

### PR DESCRIPTION
**Pull request by jack-lewin**
In response to #39! Main changes:
- Added `getDayLabel` and `getDateLabel` functions to `dateFormatter`
- Changed the forecast to a horizontal layout, reverts to vertical layout on smaller screens
- Hide nav search bar on smaller screens
- Refactored some repeated SCSS

Feedback/suggestions welcome!

### CODE REVIEW

**Comment by bmorelli25** [comment]
Hey @jack-lewin. Thanks for your PR! Unfortunately, since you've submitted I've merged a number of PR's and the code base has changed quite a bit. Can you fix the conflicts between your branch and the master branch so I can take a look at what you've done?

Thanks!

**Comment by jack-lewin** [comment]
@bmorelli25 sure thing, I'll take a look at merging the new commits :-)

**Comment by jack-lewin** [comment]
@bmorelli25 cloned the latest version of your code bade & re-applied my changes to the latest version. Hopefully my latest commit (a374344) should reflect that, despite GitHub saying there are conflicts?

**Comment by bmorelli25** [comment]
Hey @jack-lewin. Sorry for the delay.

Unfortunately Github still wont allow me to merge due to conflicts. I've got a few other merges to make, then I'll attempt to resolve the conflicts myself on your code. I'll keep you updated.

**Comment by bmorelli25** [comment]
Hey @jack-lewin. Sorry for the delay. I'd still like to get this PR merged in, just haven't quite had the time to refactor the code.

**Pull request closed without merging**
