### PR TITLE
Use the 5 day/3 hour API to return the 5 day forecast for searched city

### PR DESCRIPTION
**Pull request by kopijunkie**
- Makes a call to the API for the 5-day forecast data and displays a summary for each day #1 
- Added Weather Icon to have a visual element for each day's forecast to break up the text a bit (might need a review of how I've laid out the 5-day forecast)
- Added some notes about the data displayed

### CODE REVIEW

**Comment by bmorelli25** [comment]
@kopijunkie, This is Fantastic!! Very nicely done. I love your layout of the 5 day forecast. I removed your 'today' text in WeatherMessage.jsx as it was conflicting with an earlier merge. Other than that, things look great. Merging and closing. Please feel free to keep contributing!!

**Comment by kopijunkie** [comment]
@bmorelli25 cool. had fun working on this project. i was thinking of possibly using Moment.js to format the dates to a more human readable format as a UI improvement.

**Comment by bmorelli25** [comment]
Hah, I was thinking the same thing - using moment to add days of the week. This PR also got me thinking about a ton of over changes/improvements that could be implemented:
- Maybe there is a button where you can select if you want to see current weather or the 5 day forecast
- Custom background colors for each day of the week depending on the forecast
- Formatting the current weather in the same way that you have done with the 5 day forecast

Not gonna lie, this was one of the improvements I was really hoping someone would do. It opens the door to so many cool features

**Comment by kopijunkie** [comment]
oh, yeah. definitely has opened the door for more features now that there's more data to play around with. will start with the date display formatting with Moment.js as I think that will be a handy thing to have access to.

**Comment by bmorelli25** [comment]
Awesome. Moving the conversation to issue #17.

**Pull request merged**
