### PR TITLE
Feature api data fetch tests

### PR DESCRIPTION
**Pull request by tetreault**
Add in 8 Mocha tests to test the 2 OpenWeatherMap API functions. 

Tests include: 
- Checking for OpenWeatherMap existence. 
- Testing valid uses of OpenWeatherMap.getCurrentWeather().
- Raising an error for OpenWeatherMap.getCurrentWeather().
- Testing valid uses of OpenWeatherMap.get5DayForecast().
- Raising an error for OpenWeatherMap.get5DayForecast().

### CODE REVIEW

**Comment by bmorelli25** [comment]
@tetreault Great work! Tested and working on my end. Only thing I did was removed an extra while line you had in `openWeatherMap.jsx` for some reason. Other than that, looks great! Merging and closing. Looking forward to your other tests!

**Comment by tetreault** [comment]
Awesome, thank you!

**Comment by schmalzs** [comment]
@tetreault, @bmorelli25 - quick question...how do you pass in a value for `API_KEY` when executing the tests?  When I run `npm test` right now, I'm getting failures due to the key not being defined: `ReferenceError: API_KEY is not defined`

Thanks!

**Comment by tetreault** [comment]
@scott-schmalz Honestly... I was lazy and half assed that when I saw the error. Since I was testing the API and for some reason my .env file wasn't being read, thus API_KEY wasn't available to me I just added `const API_KEY = SOMEKEY` to the openWeatherMap.jsx file and made sure to remove it when i submitted my PR. Hopefully @bmorelli25 might have some more insight into the .env not being read properly.

**Comment by schmalzs** [comment]
No worries, thanks for the quick reply, @tetreault!

**Comment by bmorelli25** [comment]
#29, thanks Scott

**Pull request merged**
